package testPack;

// Generated by Selenium IDE

import Pages.ContactUsPage;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;


import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.IOException;
import java.io.FileReader;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.logging.log4j.*;

public class ContactUsTest {
    private WebDriver driver;
    private Logger logger;
    JavascriptExecutor js;
    private JSONArray contactUsInfo;


    @Before
    public void setUp() {

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        logger = LogManager.getLogger(ContactUsPage.class);


        try {
            JSONParser jsonParser = new JSONParser();
            FileReader reader;
            reader = new FileReader("contactUs.json");
            //Read JSON file
            contactUsInfo = (JSONArray) jsonParser.parse(reader);


        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }
    }

    @After
    public void tearDown() {
        // driver.quit();
    }

    @Test
    public void runTest() throws InterruptedException {
        // Open the Atid Store website at the contact us page
        driver.get("https://atid.store/contact-us/");
        driver.manage().window().setSize(new Dimension(1024, 670));


        logger.info("---------------------CONTACT US TEST---------------------");
        ContactUsPage contactUsPage = new ContactUsPage(driver);

        for (Object o : contactUsInfo) {
            JSONObject obj = (JSONObject) o;

            contactUsPage.enterName((String) obj.get("name"));
            if (((String) obj.get("name")).isEmpty() || ((String) obj.get("name")).equalsIgnoreCase("")) {
                logger.info("The name is empty - BAD.");
            } else {
                logger.info("The name is valid - GOOD.");
            }

            contactUsPage.enterSubject((String) obj.get("subject"));
            if (((String) obj.get("subject")).length() >= 50) {
                logger.info("The subject is longer than 50 chars - BAD.");
            } else {
                logger.info("The subject is valid - GOOD.");
            }

            contactUsPage.enterEmail((String) obj.get("email"));
            if (isValidEmail((String) obj.get("email"))) {
                logger.info("The email is not valid - GOOD.");
            } else {
                logger.info("The email is valid - BAD.");
            }

            contactUsPage.enterMessage((String) obj.get("message"));
            if (((String) obj.get("message")).isEmpty() || ((String) obj.get("message")).equalsIgnoreCase("")) {
                logger.info("The message is not valid - BAD.");
            } else if ((((String) obj.get("message")).length() >= 300)) {
                logger.info("The message is longer than 300 chars - BAD.");
            } else {
                logger.info("The message is valid - GOOD.");
            }


            contactUsPage.clickSend();

            // Check if the heading is visible
            if (contactUsPage.confirmNotPresent()) {
                logger.info("The message wasn't sent.");
            } else {
                logger.info("The message was sent.");
            }
            logger.info("----------------------------------------------------------");

            Thread.sleep(1000);
            driver.get("https://atid.store/contact-us/");

        }


    }

    public static boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }


    public static void main(String args[]) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(ContactUsTest.class);

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}