package testPack;


// Generated by Selenium IDE
import Pages.StorePage;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import org.apache.logging.log4j.*;

public class SwitchPages {
  private WebDriver driver;
  private Logger logger;
  private String baseUrl = "https://atid.store/store/";
  JavascriptExecutor js;
  @Before
  public void setUp() {

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    logger=LogManager.getLogger(SwitchPages.class);
  }
  @After
  public void tearDown() {
 // driver.quit();
  }

  
  
  @Test
  public void runTest() {
      // Open the Atid Store website
      driver.get("https://atid.store/store/");
      driver.manage().window().setSize(new Dimension(1024, 670));
      logger.info("---------------------SWITCHING PAGES TEST---------------------");

      // Log information about opening the first store page
      logger.info("Opening the first store page - GOOD");
      
      WebElement unorderedList = driver.findElement(By.className("page-numbers"));
      List<WebElement> listItems = unorderedList.findElements(By.tagName("li"));
      ArrayList<String>pageNames = new ArrayList<String>();

      StorePage storePage = new StorePage(driver);
      
      //-> test
      logger.info("starting -> test");
      int i=0;
      for (WebElement listItem : listItems) {
          String text = listItem.getText();
          if(!(text.equalsIgnoreCase("1")) && Character.isDigit(text.charAt(0))) {
          pageNames.add(driver.getCurrentUrl()+"page/"+text+"/");
          logger.info(pageNames.get(i));
          int textInt = Integer.valueOf(text);
          //start test
          logger.info("Step "+(textInt-1)+" Press '->' to switch to page number "+(textInt)+" - GOOD\"");

          if (!storePage.arrowElementPresent()) {
              logger.info("there is no next page");
          } else {
              logger.info("next");
              if(driver.getCurrentUrl().equals(pageNames.get(i))) {
            	  logger.info("good");
              }
          }
          i++;
          }         
         
      }
      
      //<-
      logger.info("starting <- test");
      i = listItems.size() - 1;
      Collections.reverse(listItems);
      for (WebElement listItem : listItems) {
          String text = listItem.getText();
          if(!(text.equalsIgnoreCase("1")) && Character.isDigit(text.charAt(0))) {
              pageNames.add(driver.getCurrentUrl()+"page/"+text+"/");
              if(i < pageNames.size()) {
                  logger.info(pageNames.get(i));
                  int textInt = Integer.valueOf(text);
                  //start test
                  logger.info("Step "+(textInt+1)+" Press '<-' to switch to page number "+(textInt)+" - GOOD\"");
                  if (!storePage.arrowElementPresent()) {
                      logger.info("there is no previous page");
                  } else {
                      logger.info("previous");
                      if(driver.getCurrentUrl().equals(pageNames.get(i))) {
                          logger.info("good");
                      }
                  }
                  i--;
              }
          }
      }
      
      

  }
public static void main(String args[]) {
	  JUnitCore junit = new JUnitCore();
	  junit.addListener(new TextListener(System.out));
	  org.junit.runner.Result result = junit.run(SwitchPages.class); // Replace "SampleTest" with the name of your class
	  if (result.getFailureCount() > 0) {
	    System.out.println("Test failed.");
	    System.exit(1);
	  } else {
	    System.out.println("Test finished successfully.");
	    System.exit(0);
	  }
	}
}